server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    routes:
      - id: reservation-servicef
        uri: lb://RESERVATION-SERVICE
        predicates:
          - Path=/reservation/**
      - id: ticket-service
        uri: lb://TICKETSERVICE
        predicates:
          - Path=/ticket/**
      - id: ticket-stock-service
        uri: lb://TICKET-STOCK-SERVICE
        predicates:
          - Path=/ticket-stock/**