server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservation/**
            - Method=POST, PUT, DELETE
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/v1/stocks/**
            - Method=POST, PUT, DELETE
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/tickets/**
            - Method=POST, PUT, DELETE
        - id: query-service
          uri: lb://query-service
          predicates:
            - Path=/api/v1/queries/**
            - Method=GET